### ISSUE TITLE
Impossible to intall

### ISSUE THREAD

**Issue by victorsanchezarevalo** [anitalu724/MutScape#5]
Hi

I am currently attempting to install MutScape using Conda, but I am encountering difficulties as the installation process seems to be unsuccessful.

I have followed the specified steps, but it appears that there might be an issue with the installation. I would greatly appreciate any guidance or assistance you could provide to troubleshoot and resolve this matter.

Best

Victor

**Comment by jess789550** [comment]
Just to add to this I also have installation issues. 

I managed to install PyVCF through #1. 

sklearn is deprecated and scikitlearn is not available for Python 3.7.

I can't install scarHRD.

Here are the commands that I ran:

```
> wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.9.2-Linux-x86_64.sh
> sha256sum Miniconda3-py37_4.9.2-Linux-x86_64.sh
> bash Miniconda3-py37_4.9.2-Linux-x86_64.sh
> export PATH="$HOME/miniconda3/bin:$PATH"

# If I didn't define python=3.7 it would default to 3.13
> conda create --name MutScape python=3.7
> conda activate MutScape

> git clone https://github.com/anitalu724/MutScape.git

> conda install -c anaconda pip

> cd MutScape/mutscape
> bash installation/install_module.sh

# Gets stuck installing scanHRD
Install scarHRD...
 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 

# Gets stuck installing r-devtools
> conda install -c conda-forge r-devtools
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 

# Another issue which was fixed by #1 was installing PyVCF
> python3 dataPreprocess.py \
-f examples/tsv/testData_maf.tsv \
-mf GI [1:3] \
-o examples/output \
-m examples/meta 
Traceback (most recent call last):
  File "/largedata/share/stp/jessk/MutScape/MutScape/mutscape/dataPreprocess.py", line 10, in <module>
    from lib.load_tsv import *
  File "/largedata/share/stp/jessk/MutScape/MutScape/mutscape/lib/load_tsv.py", line 12, in <module>
    from .vcf_tool import *
  File "/largedata/share/stp/jessk/MutScape/MutScape/mutscape/lib/vcf_tool.py", line 9, in <module>
    import vcf
ModuleNotFoundError: No module named 'vcf'

> conda install conda-forge::pyvcf
```

Any suggestions for resolving this would be appreciated.

Thank you! :) 

(Note for authors: duplicate issue #7)
